"""Init DB

Revision ID: d24d337f7bfa
Revises: 
Create Date: 2025-07-15 15:44:14.873175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24d337f7bfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('LATE_CHECK_IN', 'SOON_CHECK_OUT', 'LACK_WORKING_HOURS', 'INVALID', name='tagname'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESIGNED', 'TERMINATED', 'RETIRED', name='employeestatus'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='employeerole'), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_employee_id'), 'employee_schemas', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_id'), 'balance', ['id'], unique=False)
    op.create_table('day_timekeeping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('checkin', sa.DateTime(), nullable=True),
    sa.Column('checkout', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_information',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('position', sa.Enum('IT', 'QA', 'BA', 'TESTER', 'PM', name='employeeposition'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_schemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('leave_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('ANNUAL', 'PAID', 'UNPAID', 'MATERNITY', 'PATERNITY', 'OTHER', name='requesttype'), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REJECTED', 'APPROVED', name='requeststatus'), server_default='PENDING', nullable=False),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_schemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employee_schemas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_request_id'), 'leave_request', ['id'], unique=False)
    op.create_table('month_time_keeping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('working_hours', sa.Integer(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('is_full_attendance', sa.Boolean(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary',
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('day_timekeeping_black_tag',
    sa.Column('day_timekeeping_id', sa.Integer(), nullable=False),
    sa.Column('black_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['black_tag_id'], ['black_tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['day_timekeeping_id'], ['day_timekeeping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day_timekeeping_id', 'black_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_timekeeping_black_tag')
    op.drop_table('salary')
    op.drop_table('month_time_keeping')
    op.drop_index(op.f('ix_leave_request_id'), table_name='leave_request')
    op.drop_table('leave_request')
    op.drop_table('employee_information')
    op.drop_table('day_timekeeping')
    op.drop_index(op.f('ix_balance_id'), table_name='balance')
    op.drop_table('balance')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_employee_id'), table_name='employee_schemas')
    op.drop_table('employee_schemas')
    op.drop_table('black_tag')
    # ### end Alembic commands ###
